name: Yandao
favicon: null
layout_spectrum: 0.6154118562117219
typography_spectrum: 0.6422131734434515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.11288151214830577
  lightness: 0.8026432185433805
  saturation: 0.5555270796176046
  rhythmicContrast: 0.4455813083332032
purpose: []
